server:
  port: 8085

spring:
  application:
    name: messaging-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/dating}

  datasource:
    url: jdbc:postgresql://localhost:5436/messaging_db
    username: messaging_user
    password: messaging_pass

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

clients:
  match-base-url: ${MATCH_BASE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info