server:
  port: 8088

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dating

  cloud:
    gateway:
      routes:

        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=/profile/**

        - id: discovery-service
          uri: http://localhost:8082
          predicates:
            - Path=/discovery/**

        - id: interaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/swipes/**

        - id: messaging-under-matches
          uri: http://localhost:8085
          predicates:
            - Path=/matches/*/messages,/matches/*/messages/**

        - id: match-service
          uri: http://localhost:8084
          predicates:
            - Path=/matches/**

        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: health,info